// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/tromesh/go-ent-pokemon/ent/battle"
	"github.com/tromesh/go-ent-pokemon/ent/pokemon"
)

// BattleCreate is the builder for creating a Battle entity.
type BattleCreate struct {
	config
	mutation *BattleMutation
	hooks    []Hook
}

// SetResult sets the "result" field.
func (bc *BattleCreate) SetResult(s string) *BattleCreate {
	bc.mutation.SetResult(s)
	return bc
}

// SetCreatedAt sets the "created_at" field.
func (bc *BattleCreate) SetCreatedAt(t time.Time) *BattleCreate {
	bc.mutation.SetCreatedAt(t)
	return bc
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (bc *BattleCreate) SetNillableCreatedAt(t *time.Time) *BattleCreate {
	if t != nil {
		bc.SetCreatedAt(*t)
	}
	return bc
}

// SetUpdatedAt sets the "updated_at" field.
func (bc *BattleCreate) SetUpdatedAt(t time.Time) *BattleCreate {
	bc.mutation.SetUpdatedAt(t)
	return bc
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (bc *BattleCreate) SetNillableUpdatedAt(t *time.Time) *BattleCreate {
	if t != nil {
		bc.SetUpdatedAt(*t)
	}
	return bc
}

// SetID sets the "id" field.
func (bc *BattleCreate) SetID(i int) *BattleCreate {
	bc.mutation.SetID(i)
	return bc
}

// SetContenderID sets the "contender" edge to the Pokemon entity by ID.
func (bc *BattleCreate) SetContenderID(id int) *BattleCreate {
	bc.mutation.SetContenderID(id)
	return bc
}

// SetNillableContenderID sets the "contender" edge to the Pokemon entity by ID if the given value is not nil.
func (bc *BattleCreate) SetNillableContenderID(id *int) *BattleCreate {
	if id != nil {
		bc = bc.SetContenderID(*id)
	}
	return bc
}

// SetContender sets the "contender" edge to the Pokemon entity.
func (bc *BattleCreate) SetContender(p *Pokemon) *BattleCreate {
	return bc.SetContenderID(p.ID)
}

// SetOponentID sets the "oponent" edge to the Pokemon entity by ID.
func (bc *BattleCreate) SetOponentID(id int) *BattleCreate {
	bc.mutation.SetOponentID(id)
	return bc
}

// SetNillableOponentID sets the "oponent" edge to the Pokemon entity by ID if the given value is not nil.
func (bc *BattleCreate) SetNillableOponentID(id *int) *BattleCreate {
	if id != nil {
		bc = bc.SetOponentID(*id)
	}
	return bc
}

// SetOponent sets the "oponent" edge to the Pokemon entity.
func (bc *BattleCreate) SetOponent(p *Pokemon) *BattleCreate {
	return bc.SetOponentID(p.ID)
}

// Mutation returns the BattleMutation object of the builder.
func (bc *BattleCreate) Mutation() *BattleMutation {
	return bc.mutation
}

// Save creates the Battle in the database.
func (bc *BattleCreate) Save(ctx context.Context) (*Battle, error) {
	var (
		err  error
		node *Battle
	)
	bc.defaults()
	if len(bc.hooks) == 0 {
		if err = bc.check(); err != nil {
			return nil, err
		}
		node, err = bc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*BattleMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = bc.check(); err != nil {
				return nil, err
			}
			bc.mutation = mutation
			if node, err = bc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(bc.hooks) - 1; i >= 0; i-- {
			if bc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = bc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, bc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (bc *BattleCreate) SaveX(ctx context.Context) *Battle {
	v, err := bc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bc *BattleCreate) Exec(ctx context.Context) error {
	_, err := bc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bc *BattleCreate) ExecX(ctx context.Context) {
	if err := bc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (bc *BattleCreate) defaults() {
	if _, ok := bc.mutation.CreatedAt(); !ok {
		v := battle.DefaultCreatedAt()
		bc.mutation.SetCreatedAt(v)
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		v := battle.DefaultUpdatedAt()
		bc.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (bc *BattleCreate) check() error {
	if _, ok := bc.mutation.Result(); !ok {
		return &ValidationError{Name: "result", err: errors.New(`ent: missing required field "Battle.result"`)}
	}
	if _, ok := bc.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Battle.created_at"`)}
	}
	if _, ok := bc.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "Battle.updated_at"`)}
	}
	return nil
}

func (bc *BattleCreate) sqlSave(ctx context.Context) (*Battle, error) {
	_node, _spec := bc.createSpec()
	if err := sqlgraph.CreateNode(ctx, bc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	if _spec.ID.Value != _node.ID {
		id := _spec.ID.Value.(int64)
		_node.ID = int(id)
	}
	return _node, nil
}

func (bc *BattleCreate) createSpec() (*Battle, *sqlgraph.CreateSpec) {
	var (
		_node = &Battle{config: bc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: battle.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: battle.FieldID,
			},
		}
	)
	if id, ok := bc.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := bc.mutation.Result(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: battle.FieldResult,
		})
		_node.Result = value
	}
	if value, ok := bc.mutation.CreatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: battle.FieldCreatedAt,
		})
		_node.CreatedAt = value
	}
	if value, ok := bc.mutation.UpdatedAt(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeTime,
			Value:  value,
			Column: battle.FieldUpdatedAt,
		})
		_node.UpdatedAt = value
	}
	if nodes := bc.mutation.ContenderIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   battle.ContenderTable,
			Columns: []string{battle.ContenderColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pokemon.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.pokemon_contender = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := bc.mutation.OponentIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   battle.OponentTable,
			Columns: []string{battle.OponentColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: pokemon.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.pokemon_opponent = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// BattleCreateBulk is the builder for creating many Battle entities in bulk.
type BattleCreateBulk struct {
	config
	builders []*BattleCreate
}

// Save creates the Battle entities in the database.
func (bcb *BattleCreateBulk) Save(ctx context.Context) ([]*Battle, error) {
	specs := make([]*sqlgraph.CreateSpec, len(bcb.builders))
	nodes := make([]*Battle, len(bcb.builders))
	mutators := make([]Mutator, len(bcb.builders))
	for i := range bcb.builders {
		func(i int, root context.Context) {
			builder := bcb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*BattleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, bcb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, bcb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil && nodes[i].ID == 0 {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, bcb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (bcb *BattleCreateBulk) SaveX(ctx context.Context) []*Battle {
	v, err := bcb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (bcb *BattleCreateBulk) Exec(ctx context.Context) error {
	_, err := bcb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (bcb *BattleCreateBulk) ExecX(ctx context.Context) {
	if err := bcb.Exec(ctx); err != nil {
		panic(err)
	}
}
