// Code generated by entc, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/tromesh/go-ent-pokemon/ent/battle"
	"github.com/tromesh/go-ent-pokemon/ent/pokemon"
	"github.com/tromesh/go-ent-pokemon/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	battleFields := schema.Battle{}.Fields()
	_ = battleFields
	// battleDescCreatedAt is the schema descriptor for created_at field.
	battleDescCreatedAt := battleFields[2].Descriptor()
	// battle.DefaultCreatedAt holds the default value on creation for the created_at field.
	battle.DefaultCreatedAt = battleDescCreatedAt.Default.(func() time.Time)
	// battleDescUpdatedAt is the schema descriptor for updated_at field.
	battleDescUpdatedAt := battleFields[3].Descriptor()
	// battle.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	battle.DefaultUpdatedAt = battleDescUpdatedAt.Default.(func() time.Time)
	pokemonFields := schema.Pokemon{}.Fields()
	_ = pokemonFields
	// pokemonDescName is the schema descriptor for name field.
	pokemonDescName := pokemonFields[1].Descriptor()
	// pokemon.NameValidator is a validator for the "name" field. It is called by the builders before save.
	pokemon.NameValidator = pokemonDescName.Validators[0].(func(string) error)
	// pokemonDescDescription is the schema descriptor for description field.
	pokemonDescDescription := pokemonFields[2].Descriptor()
	// pokemon.DescriptionValidator is a validator for the "description" field. It is called by the builders before save.
	pokemon.DescriptionValidator = pokemonDescDescription.Validators[0].(func(string) error)
	// pokemonDescCreatedAt is the schema descriptor for created_at field.
	pokemonDescCreatedAt := pokemonFields[5].Descriptor()
	// pokemon.DefaultCreatedAt holds the default value on creation for the created_at field.
	pokemon.DefaultCreatedAt = pokemonDescCreatedAt.Default.(func() time.Time)
	// pokemonDescUpdatedAt is the schema descriptor for updated_at field.
	pokemonDescUpdatedAt := pokemonFields[6].Descriptor()
	// pokemon.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pokemon.DefaultUpdatedAt = pokemonDescUpdatedAt.Default.(func() time.Time)
}
