// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Battle is the predicate function for battle builders.
type Battle func(*sql.Selector)

// Pokemon is the predicate function for pokemon builders.
type Pokemon func(*sql.Selector)
